baseurl = "/"
languageCode = "en-us"
title = "Welcome to Open Weed Science"
theme = "hugo-xmag"
googleAnalytics = "UA-154732608-1"
disqusShortname = "openweedsci"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 6

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    summary_length = 300
    github_edit = "https://github.com/openweedsci/OpenWeedScience/edit/master/content/"
    footer = "&copy; [Open Weed Science](https://openweedsci.org) 2020 | [Github](https://github.com/openweedsci) | [Twitter](https://twitter.com/openweedsci)"

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
    
[params.banner]
   src = "/banner/logo3.png"
   alt = "alternative text on image"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
